### ISSUE TITLE
archive items instead of delete

### ISSUE THREAD

**Issue by Nalipp** [LearnTeachCodeSeoul/todo#53]

**Comment by DaleSeo** [comment]
Safe idea!

**Comment by Nalipp** [comment]
This looks a little harder than I first thought.
I think I am going to break this down into three chunks
1. hide a todo from the screen if it has status of archived
2. change the status of an existing todo item to archive when pressing the trash button through a new post request
3. remove the delete post request

**Comment by Nalipp** [comment]
I will close this issue and make three new ones
